spring:
  #Mysql (in memory)
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emart?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: asdf
    sql-script-encoding: utf-8

  jpa:
    hibernate:
        database-platform: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        show-sql: true
