
#HTTPS
server:
  port: 8081

#spring
spring:
  application:
    name: cloud-emart-seller
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB



#Logger
logging:
  level:
    org:
      springframework: info

eureka:
   instance:
      preferIpAddress: true		#注册服务的IP，而不是服务器的名称
      client: 
         registerWithEureka: true	#向Eureka注册服务
         fetchRegistry: true		#拉取注册表的本副本
         serviceUrl: 
            defaultZone: http://localhost:8761/eureka/