server:
   port: 8000
spring:
   application:
      name: cloud-emart-zuul
ribbon:  
   ReadTimeout: 60000
   ConnectTimeout: 60000
zuul:
   sensitiveHeaders: Access-Control-Allow-Origin,Cookie,Set-Cookie  #配置头部黑名单，它包含Zuul不会传播到下游服务的敏感头部。同时意识着Authorization将被放行
   ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
   ignored-services: '*'
   prefix: /api
   host:
      connect-timeout-millis: 30000
      socket-timeout-millis: 30000
   routes:
      cloud-emart-buyer: /cloud-emart-buyer/**   #重启机器后要多等一段时间才访问，注册要有三次心跳后才注册成功
      cloud-emart-auth: /cloud-emart-auth/**
      cloud-emart-seller: /cloud-emart-seller/**
      cloud-emart-item: /cloud-emart-item/**
      cloud-emart-history: /cloud-emart-history/**
      cloud-emart-trans: /cloud-emart-trans/**


      cloud-buyer:   #静态路由
         path: /cloud-buyer/**
         url: http://localhost:8080/
   #添加代理头
   add-proxy-headers: true
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeout-in-milliseconds: 60000
            timeout:
               enabled: false
eureka:
   instance:
      preferIpAddress: true
      client: 
         registerWithEureka: true
         fetchRegistry: true
         serviceUrl: 
            defaultZone: http://localhost:8761/eureka/
logging:
   level:
      com.netflix: DEBUG
      com.bruin.cloud.zuul.filters: DEBUG