drop table if exists `BUYER`;
CREATE TABLE `BUYER` (
  `ID` 			int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` 	VARCHAR(32),
  `PASSWORD`	VARCHAR(32), 
  `EMAIL` 		VARCHAR(128),
  `MOBILE_NUMBER` 	VARCHAR(16),
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `SELLER`;
CREATE TABLE `SELLER` (
  `ID` 			int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` 	VARCHAR(32),
  `PASSWORD`	VARCHAR(32),
  `COMPANY_NAME`	VARCHAR(50),
  `GSTIN`	VARCHAR(50),
  `COMPANY_BRIEF`	VARCHAR(50),
  `POSTAL_ADDRESS`	VARCHAR(50),
  `WEBSITE`	VARCHAR(50),
  `EMAIL` 		VARCHAR(128),
  `CONTACT NUMBER` 	VARCHAR(16),
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `PURCHASEHISTORY`;
CREATE TABLE `PURCHASEHISTORY` (
  `ID` 			int(11) NOT NULL AUTO_INCREMENT,
  `BUYER_ID` 	int(11) NOT NULL,
  `SELLER_ID` 	int(11) NOT NULL,
  `TRANSACTION_ID` 	int(11) NOT NULL,
  `ITEM_ID` 	int(11) NOT NULL,
  `NUMBER_OF_ITEMS` 	int(11) NOT NULL,
  `DATE_TIME` 	VARCHAR(8),
  `REMARKS` 	VARCHAR(50),
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


drop table if exists `DISCOUNT`;
CREATE TABLE `DISCOUNT` (
  `ID` 			int(11) NOT NULL AUTO_INCREMENT,
  `DISCOUNT_CODE` 	VARCHAR(8),
  `PERCENTAGE` 	FLOAT(8),
  `START_DATE` 	VARCHAR(8),
  `END_DATE` 	VARCHAR(8),
  `DESCRIPTION` 	VARCHAR(50),
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `TRANSACTION`;
CREATE TABLE `TRANSACTION` (
  `ID` 			int(11) NOT NULL AUTO_INCREMENT,
  `BUYER_ID` 	int(11) NOT NULL,
  `SELLER_ID` 	int(11) NOT NULL,
  `TRANSACTION_TYPE` 	VARCHAR(8),
  `DATE_TIME` 	VARCHAR(8),
  `REMARKS` 	VARCHAR(50),
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


drop table if exists `ITEM`;
CREATE TABLE `ITEM` (
  `ID` 			int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` 	int(11) NOT NULL,
  `SUBCATEGORY_ID` 	int(11) NOT NULL,
  `PRICE` 	VARCHAR(50),
  `ITEM_NAME` 	VARCHAR(50),
  `DESCRIPTION` 	VARCHAR(50),
  `STOCK_NUMBER` 	int(11),
  `REMARKS` 	VARCHAR(50),
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `CATEGORY`;
CREATE TABLE `CATEGORY` (
  `ID` 			int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_NAME` 	VARCHAR(50),
  `BRIEF_DETAILS` 	VARCHAR(50),
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


drop table if exists `SUBCATEGORY`;
CREATE TABLE `SUBCATEGORY` (
  `ID` 			int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` 			int(11) NOT NULL,
  `SUBCATEGORY_NAME` 	VARCHAR(50),
  `BRIEF_DETAILS` 	VARCHAR(50),
  `GST` 	VARCHAR(50),
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



