drop table if exists `BUYER`;
CREATE TABLE `BUYER` (
  `ID` 			int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` 	VARCHAR(32),
  `PASSWORD`	VARCHAR(32), 
  `EMAIL` 		VARCHAR(128),
  `MOBILE_NUMBER` 	VARCHAR(16),
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;